### ISSUE TITLE
df_orig.pkl not found

### ISSUE THREAD

**Issue by nehruperumalla** [opokualbert/Domain_Specific_Word2Vec_Word_Embedding_Model_with_Gensim#1]
df_orig.pkl is not present in the repo but using it ipynb.

**Comment by opokualbert** [comment]
Apologies and sorry for the confusion. The pickled data is from a previous tutorial shared here. Read the Jupyter notebook up to cell 10.
https://github.com/opokualbert/Topic-Modeling-with-Non-Negative-Matrix-Factorization-NMF-/blob/master/Consumer%20Financial%20Complaint%20Topic%20Modeling-Data%20Prep%20part1.ipynb
